server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 353873951299-p6v7kpm7l0aj73jcdee4073ed8i6g388.apps.googleusercontent.com
            client-secret: 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

  application:
    name: Trading Backend
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/trading
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  jwt:
    secret: b2f3e05b0b0f0e0ebe95d19c37fcf236bb3dd29f4cd00b946e27d7c6cfd199e6
    expiration: 864000000
  refresh:
    expiration: 8640000000
  razorpay:
    key: rzp_test_cvU9Jl9tV7jPhV
    secret: ZZNfWiq2LJSMWLVrYW2Q9iyj